spring.application.name=iot

spring.datasource.url=jdbc:mysql://localhost:3306/smart_home
spring.datasource.username=root
spring.datasource.password=123456v

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
